name: Build and package

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: src/GithubActionsDemo/GithubActionsDemo/GithubActionsDemo.csproj
  SETTTINGS_FILE: src/GithubActionsDemo/GithubActionsDemo/appsettings.json
  APP_VERSION: $(date +'%Y.%-m.%-d')

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_NAME }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish ${{ env.PROJECT_NAME }} --configuration Release --no-restore --output ./publish

      - name: Set version
        run: echo ${{ env.APP_VERSION }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-app
          path: ./publish