name: Build and package

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: src/GithubActionsDemo/GithubActionsDemo/GithubActionsDemo.csproj
  SETTINGS_FILE: publish/appsettings.json
  CURRENT_DATE: $(date +'%Y.%-m.%-d')
  MINUTES_SINCE_MIDNIGHT: $(($(date +'%-H * 60 + %-M')))

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_NAME }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish ${{ env.PROJECT_NAME }} --configuration Release --no-restore --output ./publish

      - name: Update version in settings file
        run: |
          APP_VERSION="${{ env.CURRENT_DATE }}.${{ env.MINUTES_SINCE_MIDNIGHT }}"
          echo $APP_VERSION
          jq --arg version "$APP_VERSION" '.Version = $version' ${{ env.SETTINGS_FILE }} > temp.json && mv temp.json ${{ env.SETTINGS_FILE }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-app
          path: ./publish