name: Deploy

env:
  DOTNET_VERSION: '8.0.x'

on:
  workflow_dispatch:
    inputs:
      siteToDeploy:
        description: 'Demo site to deploy'
        required: true
        default: 'test-web-app-maisak'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get latest run id
        id: get-latest-run-id
        run: |
          latest_run_id=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/runs" \
          | jq -r '.workflow_runs[0].id')
          echo "LATEST_RUN_ID=$latest_run_id" >> $GITHUB_ENV
        shell: bash

      - name: Debugging
        run: |
          echo "hi"
          echo ${{ env.LATEST_RUN_ID }}
            
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: demo-app
          github-token: ${{ secrets.PAT }}
          run-id: ${{ env.LATEST_RUN_ID }}
          
      - name: Echo
        run: |
          echo "hi"
          echo ${{ inputs.siteToDeploy }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.siteToDeploy }}
          publish-profile: ${{ secrets.AZURE_DEMO_PUBLISH_PROFILE }}
          package: '.'