name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get latest run id
        id: get-latest-run-id
        run: |
          latest_run_id=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/runs" \
          | jq -r '.workflow_runs[0].id')
          echo $latest_run_id
        shell: bash

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: demo-app
          github_token: ${{ secrets.PAT }}
          path: ./downloads          
          run-id: ${{ env.LATEST_RUN_ID }}