name: Build and package

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_NAME: src/AwesomePrivatePackage/AwesomePrivatePackage.csproj

on:
  push:
    branches:
      - package
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_NAME }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack ${{ env.PROJECT_NAME }} --configuration Release --no-restore --output ./publish

      - name: Push to the packages
        run: dotnet nuget push ./publish/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json